// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Ungureanu_Gabriel_Sebastian_CIG7.Data;

#nullable disable

namespace Ungureanu_Gabriel_Sebastian_CIG7.Migrations
{
    [DbContext(typeof(Ungureanu_Gabriel_Sebastian_CIG7Context))]
    [Migration("20230119144310_CompanieMig")]
    partial class CompanieMig
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Ungureanu_Gabriel_Sebastian_CIG7.Models.Bilet", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<int?>("CompanieID")
                        .HasColumnType("int");

                    b.Property<string>("Destinatie")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OraPlecarii")
                        .HasColumnType("datetime2");

                    b.Property<int?>("OrasID")
                        .HasColumnType("int");

                    b.Property<decimal>("Pret")
                        .HasColumnType("decimal(6,2)");

                    b.HasKey("ID");

                    b.HasIndex("CompanieID");

                    b.HasIndex("OrasID");

                    b.ToTable("Bilet");
                });

            modelBuilder.Entity("Ungureanu_Gabriel_Sebastian_CIG7.Models.Companie", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("Adresa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Anulinfiintari")
                        .HasColumnType("datetime2");

                    b.Property<string>("CompanieN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Companie");
                });

            modelBuilder.Entity("Ungureanu_Gabriel_Sebastian_CIG7.Models.Oras", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<DateTime>("OraDeschidere")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("OraInchidere")
                        .HasColumnType("datetime2");

                    b.Property<string>("OrasGara")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Strada")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Oras");
                });

            modelBuilder.Entity("Ungureanu_Gabriel_Sebastian_CIG7.Models.Bilet", b =>
                {
                    b.HasOne("Ungureanu_Gabriel_Sebastian_CIG7.Models.Companie", "Companie")
                        .WithMany("Bilete")
                        .HasForeignKey("CompanieID");

                    b.HasOne("Ungureanu_Gabriel_Sebastian_CIG7.Models.Oras", "Oras")
                        .WithMany("Bilete")
                        .HasForeignKey("OrasID");

                    b.Navigation("Companie");

                    b.Navigation("Oras");
                });

            modelBuilder.Entity("Ungureanu_Gabriel_Sebastian_CIG7.Models.Companie", b =>
                {
                    b.Navigation("Bilete");
                });

            modelBuilder.Entity("Ungureanu_Gabriel_Sebastian_CIG7.Models.Oras", b =>
                {
                    b.Navigation("Bilete");
                });
#pragma warning restore 612, 618
        }
    }
}
